name: playbook_generator
description: Playbook Generator Package
version: 1.2.0
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: ^3.8.0

resolution: workspace

dependencies:
  analyzer: ^8.0.0
  build: ^4.0.0
  source_gen: ^4.0.0
  path: ^1.9.0
  glob: ^2.1.2
  code_builder: ^4.10.0
  dart_style: ^3.0.1

dev_dependencies:
  very_good_analysis: ^9.0.0
