include: package:very_good_analysis/analysis_options.5.1.0.yaml

analyzer:
  exclude:
    - '**/generated_playbook.dart'

linter:
  rules:
    sort_pub_dependencies: false
    flutter_style_todos: false
    public_member_api_docs: false
    one_member_abstracts: false
    always_put_required_named_parameters_first: false
