name: Playbook
repository: https://github.com/playbook-ui/playbook-flutter

packages:
  - packages/**
  - examples/**

ide:
  intellij: true

command:
  version:
    linkToCommits: true

  bootstrap:
    hooks:
      post:
        run: |
          melos gen

scripts:
  format: melos exec -- flutter format .

  analyze: melos exec -- flutter analyze .

  clean: melos exec -- flutter clean

  upgrade:
    run: |
      melos exec -- flutter pub upgrade
      melos bootstrap

  get:
    run: melos exec -- flutter pub get

  gen:
    run: melos gen:all --no-select

  gen:all:
    run: |
      melos exec -- dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

  test:
    run: melos test:snapshot --no-select

  test:snapshot:
    run: |
      melos exec -- flutter test --update-goldens
    packageFilters:
      dependsOn:
        - playbook_snapshot
      dirExists:
        - test

  test:all:
    run: |
      melos exec -- flutter test --update-goldens
    packageFilters:
      dirExists:
        - test
