name: playbook_snapshot
description: Playbook Snapshot package.
version: 1.2.0
repository: https://github.com/playbook-ui/playbook-flutter
documentation: https://github.com/playbook-ui/playbook-flutter
issue_tracker: https://github.com/playbook-ui/playbook-flutter/issues

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

resolution: workspace

dependencies:
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

  playbook: ^1.0.0
  yaml: ^3.1.2

dev_dependencies:
  very_good_analysis: ^10.0.0
